"""
sinopsis_manual.py — sinopsis yang ditulis tangan, bukan hasil panggilan API.

Tiga aturan yang dipegang saat menulisnya:

1. Buku yang isinya benar-benar dikenali ditulis ringkasan ceritanya.
2. Buku pelajaran, kamus, ensiklopedia, dan panduan dijelaskan pokok
   bahasannya sebagaimana terbaca dari judul dan mata pelajarannya. Itu
   keterangan, bukan karangan.
3. Karya sastra yang alurnya tidak diketahui TIDAK dikarang. Yang ditulis
   hanya yang pasti — bahasa, bentuk karya, dan penulisnya — lalu pembaca
   diarahkan bertanya ke petugas. Sinopsis kosong lebih baik daripada
   sinopsis palsu di katalog perpustakaan.
"""

SINOPSIS = {}

SINOPSIS.update({
269: "Buku bacaan ringan yang mengajak pembaca muda memahami arti berbagi dengan orang di sekitarnya. Ditulis dengan bahasa sederhana sehingga mudah diikuti siswa SMP.",
272: "Prof. Amin Syukur menuturkan pengalamannya menghadapi penyakit berat dengan bersandar pada zikir dan ketenangan batin. Memadukan pengalaman pribadi dengan pandangan keagamaan tentang sabar dan ikhtiar.",
273: "Buku motivasi keislaman yang mengajak pembaca menjalani hidup dengan lapang dan tidak memaksakan keadaan. Berisi renungan tentang menerima takdir sambil tetap berusaha.",
274: "Panduan keislaman tentang cara memandang dan menjemput rezeki dalam kehidupan keluarga. Membahas adab, doa, dan usaha yang dianjurkan agama.",
275: "Membahas prinsip berdagang yang dicontohkan Rasulullah, seperti kejujuran, amanah, dan pelayanan yang baik. Cocok untuk mengenal etika bisnis dari sudut pandang Islam.",
276: "Panduan beretika di media sosial menurut tuntunan Islam. Membahas cara menyaring kabar, menjaga lisan saat menulis, dan menghindari perselisihan di dunia maya.",
277: "Buku tentang mendidik anak dan remaja muslim di tengah dunia digital. Membahas tantangan zaman sekarang dan cara mendampingi generasi muda menghadapinya.",
278: "Buku pengembangan diri yang membahas cara menata pikiran agar lebih tenang dan bahagia. Berisi latihan sederhana untuk mengelola stres dan pikiran negatif.",
279: "Panduan mewujudkan sekolah dan madrasah yang aman serta nyaman bagi anak. Membahas hak anak, pencegahan kekerasan, dan peran guru dalam menciptakan lingkungan ramah.",
280: "Panduan tata cara salat yang disusun berdasarkan hadis-hadis sahih. Menjelaskan gerakan dan bacaan salat beserta rujukan dalilnya.",
281: "Pedoman salat khusus bagi muslimah, mencakup tata cara, ketentuan aurat, dan hal yang berkaitan dengan ibadah perempuan. Disusun ringkas sebagai pegangan sehari-hari.",
282: "Tahun kedua Harry Potter di Hogwarts. Sekolah digemparkan oleh terbukanya Kamar Rahasia dan serangkaian serangan yang membuat murid membatu. Bersama Ron dan Hermione, Harry menelusuri legenda kuno sekolah untuk mengungkap dalangnya.",
283: "Novel remaja Indonesia karya Triani Retno A. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan untuk keterangan lebih rinci.",
284: "Novel remaja karya Indah Riyana yang populer di kalangan pembaca muda. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan.",
285: "Novel remaja karya Oda Sekar Ayu. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan untuk keterangan lebih rinci.",
286: "Novel remaja karya Asbell Audida. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan untuk keterangan lebih rinci.",
287: "Kumpulan tulisan dari komunitas menulis One Week One Paper. Berisi beberapa cerita pendek karya penulis yang berbeda dalam satu buku.",
288: "Karya fiksi Indonesia karya Dimas Rio. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan untuk keterangan lebih rinci.",
289: "Menelusuri beragam tradisi Lebaran dari berbagai daerah di Nusantara. Membahas asal-usul kebiasaan seperti mudik, halalbihalal, dan sajian khas Idulfitri.",
290: "Cerita anak bertema olahraga dan perjuangan meraih cita-cita menjadi atlet. Mengangkat nilai disiplin, kerja keras, dan sportivitas.",
291: "Panduan menggunakan internet secara sehat dan aman untuk keperluan belajar. Membahas cara mencari sumber tepercaya, menjaga data pribadi, dan menghindari konten berbahaya.",
292: "Panduan literasi digital yang ditujukan bagi guru madrasah. Membahas cara menilai informasi, memanfaatkan media digital dalam mengajar, dan mendampingi siswa berinternet.",
293: "Pengantar berpikir komputasional bagi guru madrasah. Membahas cara memecah masalah, mengenali pola, dan menyusun langkah penyelesaian secara runtut.",
294: "Kumpulan dua belas cerita karya Achi TM dengan latar dunia sekolah dan kehidupan sehari-hari. Setiap kisah menyisipkan pelajaran tentang syukur dan kebahagiaan.",
295: "Panduan tentang perlindungan hukum dan profesi bagi guru di sekolah, madrasah, dan pesantren. Membahas hak, kewajiban, serta cara menghadapi persoalan yang menimpa pendidik.",
296: "Panduan pencegahan kebiasaan merokok bagi pelajar, guru, dan orang tua. Menjelaskan bahaya rokok bagi kesehatan dan cara menolak ajakan merokok.",
297: "Panduan pengenalan bahaya narkoba bagi remaja. Membahas jenis dan dampak narkoba, serta cara menghindar dari pergaulan yang berisiko.",
298: "Panduan pendidikan antikorupsi untuk siswa SMP dan MTs. Mengenalkan nilai kejujuran, tanggung jawab, dan keberanian menolak kecurangan sejak dini.",
299: "Panduan pendidikan antikorupsi untuk siswa SMP dan MTs. Mengajak siswa mengenali bentuk kecurangan di sekitarnya dan membiasakan sikap jujur.",
300: "Panduan pendidikan antikorupsi untuk jenjang SMP dan MTs. Membahas nilai integritas melalui contoh yang dekat dengan kehidupan siswa.",
301: "Panduan mencegah dan menangani perundungan di lingkungan sekolah. Ditujukan bagi siswa dan pendamping, berisi cara mengenali, melapor, dan menghentikan bullying.",
302: "Mengisahkan perjalanan hidup perempuan mulia dalam sejarah Islam. Menampilkan keteladanan mereka dalam iman, ilmu, dan pengabdian.",
303: "Komik karya Tony Wong, komikus asal Hong Kong, bergenre aksi dan petualangan. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan.",
304: "Kisah sepuluh anak Belitong yang bersekolah di SD Muhammadiyah yang nyaris ditutup karena kekurangan murid. Bersama Bu Mus dan Pak Harfan, mereka bertahan menuntut ilmu di tengah keterbatasan. Novel tentang semangat belajar, persahabatan, dan mimpi anak kampung.",
305: "Karya fiksi Indonesia karya Ricky Cuaca. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan untuk keterangan lebih rinci.",
306: "Bagian dari seri empat musim karya Ilana Tan, berlatar kota Paris. Mengisahkan pertemuan Tara Dupont dengan Tatsuya Fujisawa dan rahasia masa lalu yang menghubungkan keluarga mereka.",
307: "Kumpulan soal dan pembahasan untuk melatih kemampuan akademik. Cocok dipakai berlatih menghadapi ujian dan tes seleksi.",
308: "Buku pelajaran Bahasa Inggris untuk jenjang SMP. Berisi materi, latihan, dan kegiatan berlatih membaca, menulis, menyimak, serta berbicara.",
})

SINOPSIS.update({
309: "Buku pelajaran Pendidikan Jasmani, Olahraga, dan Kesehatan untuk kelas VII. Membahas gerak dasar, permainan olahraga, kebugaran, dan pola hidup sehat.",
310: "Buku pelajaran Prakarya untuk SMP kelas 9. Berisi materi dan panduan praktik membuat karya kerajinan, rekayasa, budidaya, atau pengolahan.",
311: "Buku pelajaran Bahasa Sunda untuk kelas 7 dengan Kurikulum Merdeka. Berisi bacaan, kosakata, dan latihan berbahasa Sunda.",
312: "Buku referensi tentang kepramukaan di Indonesia. Membahas sejarah, lambang, tingkatan, dan kegiatan kepramukaan.",
313: "Buku pengayaan sains yang membahas cahaya, cara kerja mesin, dan pengenalan fisika partikel. Disajikan dengan penjelasan dan gambar yang mudah dipahami.",
314: "Buku pengayaan sains tentang para ilmuwan, hukum dasar sains, dan reaksi kimia. Mengenalkan penemuan penting beserta tokoh di baliknya.",
315: "Buku pengayaan sains yang membahas gaya, listrik, serta sifat logam dan nonlogam. Dilengkapi contoh penerapannya dalam kehidupan sehari-hari.",
316: "Buku pengayaan sains tentang bentuk energi dan proses evolusi makhluk hidup. Menjelaskan konsepnya secara ringkas untuk pembaca pemula.",
317: "Buku pelajaran koding dan kecerdasan artifisial untuk kelas VII. Mengenalkan dasar pemrograman dan cara kerja kecerdasan buatan.",
318: "Buku pelajaran koding dan kecerdasan artifisial untuk kelas IX. Melanjutkan materi pemrograman dan penerapan kecerdasan buatan.",
319: "Buku pelajaran Bahasa Sunda untuk kelas IX dengan Kurikulum Merdeka. Berisi bacaan, tata bahasa, dan latihan berbahasa Sunda.",
320: "Buku pengayaan sains tentang ekologi. Membahas hubungan makhluk hidup dengan lingkungannya, rantai makanan, dan keseimbangan alam.",
321: "Buku pelajaran koding dan kecerdasan artifisial untuk kelas VIII. Melanjutkan dasar pemrograman dan pengenalan kecerdasan buatan.",
322: "Kamus bergambar Inggris-Indonesia. Setiap kata disertai gambar sehingga memudahkan mengingat kosakata baru.",
323: "Buku pengayaan sains tentang unsur, senyawa, dan campuran. Menjelaskan perbedaan ketiganya beserta contoh di sekitar kita.",
324: "Buku pengayaan sains tentang sel sebagai satuan terkecil makhluk hidup. Membahas bagian sel dan fungsinya.",
325: "Buku pengantar sains yang membahas cara kerja ilmu pengetahuan. Mengenalkan metode ilmiah dan berbagai cabang sains.",
326: "Buku referensi tentang keragaman seni dan budaya Indonesia. Menampilkan tarian, musik, kerajinan, dan tradisi dari berbagai daerah.",
327: "Buku pelajaran Ilmu Pengetahuan Sosial untuk SMP kelas 7. Membahas manusia, tempat, lingkungan, serta kehidupan sosial dan ekonomi.",
328: "Buku pelajaran Bahasa Sunda untuk jenjang SMP. Berisi bacaan, tata bahasa, dan latihan menggunakan bahasa Sunda.",
329: "Buku ketiga dari trilogi Negeri 5 Menara karya A. Fuadi. Mengikuti Alif setelah lulus kuliah, bekerja sebagai wartawan, lalu melanjutkan studi ke Amerika. Bercerita tentang mencari muara: tempat kembali setelah panjang merantau.",
330: "Alif meninggalkan kampungnya di Maninjau untuk menuntut ilmu di Pondok Madani. Bersama lima sahabat dari berbagai daerah, ia menatap awan yang menyerupai menara sambil membayangkan masa depan. Terkenal dengan mantra man jadda wajada, siapa bersungguh-sungguh pasti berhasil.",
331: "Buku kegiatan Ramadan untuk siswa. Berisi catatan ibadah harian, ringkasan ceramah, dan kegiatan selama bulan puasa.",
332: "Ensiklopedia sains bergambar untuk anak. Menjawab pertanyaan sehari-hari tentang alam, tubuh, dan teknologi dengan bahasa sederhana.",
333: "Ensiklopedia muatan lokal seri kedelapan yang membahas sejarah dan budaya. Menyajikan peristiwa dan warisan budaya Indonesia secara ringkas.",
334: "Buku sejarah nasional Indonesia jilid kedua yang membahas zaman kuno. Menguraikan kerajaan awal beserta kehidupan masyarakatnya.",
335: "Buku sains untuk pemula jilid kelima dengan tema bunyi. Mengajak pembaca memahami bagaimana bunyi terbentuk dan merambat lewat percobaan sederhana.",
336: "Buku sejarah tentang masa prasejarah. Membahas kehidupan manusia purba, peralatan yang digunakan, dan peninggalannya.",
337: "Buku sejarah Indonesia jilid ketiga tentang tumbuh dan berkembangnya kerajaan Islam di Nusantara. Membahas jalur masuknya Islam serta kerajaan yang berdiri.",
338: "Buku sejarah nasional Indonesia yang membahas zaman prasejarah. Menguraikan pembabakan masa purba dan bukti peninggalannya.",
339: "Ensiklopedia yang memuat riwayat para pahlawan nasional Indonesia. Menampilkan perjuangan dan jasa mereka bagi kemerdekaan.",
340: "Ensiklopedia yang merangkum peristiwa penting dalam sejarah Indonesia dan dunia. Disusun sebagai rujukan cepat bagi pelajar.",
341: "Ensiklopedia geografi yang dilengkapi atlas dunia. Membahas benua, negara, iklim, dan bentang alam beserta petanya.",
342: "Menelusuri sejarah mobil sejak awal diciptakan hingga masa kini. Membahas penemunya, perkembangan mesin, dan perubahan bentuk kendaraan dari masa ke masa.",
343: "Ensiklopedia muatan lokal seri ketujuh dengan tema ilmu pengetahuan dan teknologi. Menyajikan penemuan dan penerapan teknologi secara ringkas.",
344: "Buku sains bergambar tentang tata surya. Mengenalkan matahari, planet, bulan, serta benda langit lain beserta cirinya.",
345: "Buku pengenalan matematika dengan tema bangun datar. Membahas jenis bangun, sifat, keliling, dan luasnya dengan bahasa yang mudah.",
346: "Kumpulan cara cepat dan strategi menyelesaikan soal matematika. Cocok dipakai berlatih menghadapi ulangan dan olimpiade.",
347: "Buku pelajaran Bahasa Sunda Kurikulum Merdeka untuk Fase D kelas 8. Berisi bacaan, tata bahasa, dan latihan berbahasa Sunda.",
})

SINOPSIS.update({
348: "Kumpulan tulisan Ajip Rosidi tentang kedudukan bahasa Indonesia dan tantangan yang dihadapinya. Membahas hubungan bahasa dengan jati diri bangsa.",
349: "Tragedi Yunani klasik karya Sophokles. Oidipus, raja Thebes, bersumpah mengusut pembunuhan raja terdahulu demi mengakhiri wabah, tanpa menyadari bahwa penyelidikannya menuntun pada dirinya sendiri. Kisah tentang takdir yang tidak bisa dihindari.",
350: "Novel sejarah berbahasa Sunda karya Yoseph Iskandar dengan latar Kerajaan Sunda. Mengangkat kisah kepemimpinan dan peristiwa di tanah Pasundan pada masa lampau.",
351: "Kumpulan cerita pendek karya Arianto Adipurwanto. Sinopsis tiap ceritanya belum tersedia; tanyakan pada petugas perpustakaan.",
352: "Kajian tentang Islam dan kedaerahan di Indonesia, khususnya Jawa Barat. Membahas bagaimana praktik keagamaan berkelindan dengan budaya setempat.",
353: "Kumpulan tulisan Ajip Rosidi seputar bahasa dan penggunaannya sehari-hari. Mengajak pembaca lebih cermat memilih kata.",
354: "Kajian tentang sistem pertanian tradisional masyarakat Sunda. Membahas cara bertani, kalender tanam, dan kearifan lokal yang menyertainya.",
355: "Karya sastra karya Moerwanto bertema kelautan dan kebaharian. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan.",
356: "Karya keagamaan karya Soekanto S.A. yang mengangkat tema kecintaan kepada Allah. Berisi renungan dan tuntunan bagi pembaca.",
357: "Kamus istilah bidang hubungan industri dan manajemen sumber daya manusia. Menjelaskan istilah ketenagakerjaan beserta maknanya.",
358: "Kamus istilah sastra Indonesia susunan Ajip Rosidi. Menjelaskan istilah yang sering dipakai dalam pelajaran dan kajian sastra.",
359: "Kamus bahasa Sunda susunan R. Satjadibrata, salah satu kamus Sunda yang lama menjadi rujukan. Memuat kata beserta artinya dalam bahasa Sunda.",
360: "Kamus Sunda-Indonesia susunan R. Satjadibrata. Membantu mencari padanan kata Sunda ke dalam bahasa Indonesia.",
361: "Kumpulan pemikiran Sjafruddin Prawiranegara tentang Islam sebagai tuntunan hidup. Membahas hubungan agama dengan kehidupan bermasyarakat dan bernegara.",
362: "Karya sastra berbahasa Sunda karya Nasrul Jatnika. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan.",
363: "Novel karya sastrawan Rusia Ivan Turgenev. Mengisahkan seorang pemuda yang jatuh cinta untuk pertama kalinya kepada gadis tetangga, dan kenyataan pahit yang kemudian ia temukan. Cerita tentang cinta pertama yang berakhir sebagai pelajaran hidup.",
364: "Buku pelajaran Bahasa Inggris kelas 7 dengan Kurikulum Merdeka. Berisi materi dan latihan membaca, menulis, menyimak, serta berbicara.",
365: "Buku Bimbingan dan Konseling untuk SMP kelas VII. Membahas pengenalan diri, cara belajar, pergaulan, dan perencanaan masa depan.",
366: "Novel sejarah berbahasa Sunda karya Yoseph Iskandar yang mengangkat sosok Prabu Wastu Kancana dari Kerajaan Sunda. Berlatar kehidupan istana dan masyarakat pada masa itu.",
367: "Novel sejarah berbahasa Sunda karya Yoseph Iskandar dengan latar Kerajaan Sunda. Judulnya merujuk pada tri tangtu, konsep tiga pilar penataan kehidupan dalam tradisi Sunda.",
368: "Karya sastra berbahasa Sunda karya Wahyu Wibisana. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan.",
369: "Karya sastra berbahasa Sunda karya Oman Komara. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan.",
370: "Kumpulan sajak karya Amir Hamzah, penyair Pujangga Baru. Berisi puisi bernuansa ketimuran dengan bahasa yang liris dan penuh perlambang.",
371: "Karya sastra berbahasa Sunda karya Us Tiarsa R. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan.",
372: "Karya Ajip Rosidi berbahasa Sunda yang mengangkat cermin dari sejarah Islam. Berisi renungan atas peristiwa masa lalu bagi kehidupan sekarang.",
373: "Tulisan Erry Riyana Hardjapamekas tentang korupsi sebagai persoalan budaya, bukan sekadar pelanggaran hukum. Membahas akar kebiasaan yang membuat korupsi bertahan.",
374: "Esai Ajip Rosidi yang mempertanyakan kapan sesungguhnya kesusastraan Indonesia lahir. Membahas tonggak dan perdebatan dalam sejarah sastra Indonesia.",
375: "Empat kumpulan sajak karya Ajip Rosidi dalam satu buku. Menampilkan perjalanan kepenyairannya dari waktu ke waktu.",
376: "Karya klasik sastra Sunda karya Moh. Ambri. Mengangkat kisah bernuansa kepercayaan masyarakat tentang jalan pintas mencari kekayaan dan akibat yang menyertainya.",
377: "Karya berbahasa Sunda karya Sjarif Amin yang menuturkan lakon kehidupan seorang jurnalis. Mengangkat dunia kewartawanan dari sudut pandang pelakunya.",
378: "Novel klasik berbahasa Sunda karya Moh. Sanoesi. Mengisahkan perjalanan hidup Siti Rayati dari keadaan gelap dan hina menuju terang dan mulia, sebagaimana tersirat pada anak judulnya.",
379: "Cerita berbahasa Sunda tentang keberanian tokoh pahlawan Islam. Disajikan sebagai bacaan yang mengandung keteladanan.",
380: "Karya berbahasa Sunda karya Risnawati bertema perjalanan ke pesisir. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan.",
381: "Karya sastra karya Moerwanto bertema semangat kepahlawanan. Sinopsis lengkapnya belum tersedia; tanyakan pada petugas perpustakaan.",
382: "Buku Bimbingan dan Konseling jilid kedua untuk SMP. Membahas pengembangan diri, hubungan sosial, dan kesiapan belajar.",
383: "Buku Bimbingan dan Konseling jilid ketiga untuk SMP. Membahas perencanaan karier, kemandirian, dan persiapan melanjutkan sekolah.",
})
